{
 "title": "Talaiot",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "query": "influxdb" },
   { "name": "db", "query": "SHOW DATABASES" },
   {
    "name": "rp",
    "query": "show retention policies on \"$db\""
   },
   {
    "name": "requestedTasks",
    "query": "show tag values on \"$db\" with key = \"task\""
   },
   {
    "name": "performance_slice",
    "query": "osVersion,javaVmName,cpuCount,username,gradleVersion"
   },
   {
    "name": "buildMachine",
    "query": "SELECT distinct(buildMachine) FROM \"rpTalaiot\".\"build\" WHERE $timeFilter"
   }
  ]
 },
 "panels": [
  {
   "title": "General metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "$buildMachine avg buildTime",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "SELECT \"duration\" FROM \"rpTalaiot\".\"build\" WHERE (buildMachine = '$buildMachine') AND $timeFilter"
    }
   ]
  },
  {
   "title": "Builds",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Start time",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"start\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter  AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "username",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT username FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "branch",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT gitBranch FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "cacheRatio",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT cacheRatio FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"duration\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "gradleVersion",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT gradleVersion FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"success\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "root project",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"rootProject\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "requestedTasks",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"requestedTasks\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "scan link",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"scanLink\" FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "os version",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT osVersion FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter AND buildMachine != ''",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "buildMachine",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "task",
     "query": "SELECT buildMachine FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "buildMachine" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Overall tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cached tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='FROM_CACHE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Up-to-date tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='UP_TO_DATE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Executed tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 5, "x": 15, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='EXECUTED'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "No source tasks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT count(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"state\"='NO_SOURCE'",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Duration [mean]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration\") FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter GROUP BY requestedTasks, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Configuration [mean]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "[[tag_requestedTasks]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"configuration\") FROM \"$db\".\"$rp\".\"build\" WHERE $timeFilter GROUP BY requestedTasks, time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Task breakdown",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "[[tag_state]]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"value\") FROM \"$db\".\"$rp\".\"task\" WHERE $timeFilter AND \"rootNode\" = 'false' GROUP BY state,time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "buildMachines avg duration", "type": "barchart", "gridPos": { "h": 8, "w": 24, "x": 0, "y": 37 }, "fieldConfig": { "defaults": { "unit": "ms" } } },
  {
   "title": "Task drilldown",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "P90 for $requestedTasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "[[tag_requestedTasks]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "P50 for $requestedTasks",
     "type": "stat",
     "gridPos": { "h": 5, "w": 11, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "alias": "[[tag_requestedTasks]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"duration\", 50) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Max workers P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Max Gradle workers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"maxWorkers\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Task cache ratio P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Max Gradle workers",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"cacheRatio\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"task\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Xms P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 8, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Xms",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"javaXmsBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Xmx P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 11, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "alias": "Xmx",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"javaXmxBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "RAM available P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 14, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"totalRamAvailableBytes\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CPU count P90",
     "type": "stat",
     "gridPos": { "h": 3, "w": 3, "x": 17, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"cpuCount\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"requestedTasks\"='$requestedTasks' AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Performance slices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "repeat": "performance_slice",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Duration of $requestedTasks [P90] by $performance_slice",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 77 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "$tag_$performance_slice",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT percentile(\"duration\", 90) FROM \"$db\".\"$rp\".\"build\" WHERE \"task\"='$requestedTasks' AND $timeFilter GROUP BY $performance_slice, time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  }
 ]
}